Removed new line char "\n" from "version"
New line char causes an error over NXRM. Removed new line "\n" from version. 
Auto-Closed PR: https://github.com/CocoaPods/Specs/pull/14429

CDN: *****-repository-cocoapods-proxy URL couldn't be downloaded: https://*******/repository/cocoapods-proxy/Specs/9/4/5/RealmSwift/0.92.1/RealmSwift.podspec.json Response: 500

javax.servlet.ServletException: java.lang.IllegalArgumentException: Illegal character in path at index 22: pods/RealmSwift/0.92.1
/https/api.github.com/repos/realm/realm-cocoa/tarball/v0.92.1.tar.gz